### ISSUE TITLE
Build error cennznet-runtime-template

### ISSUE THREAD

**Issue by nazmul49** [cennznet/xpay-runtime-tutorial#1]
I have tried to build the cennznet-runtime-template following the README file but found build error.
Environment: Ubuntu 18 LTS
rustc version: 1.39.0
cargo version: 1.39.0
Here is my terminal snapshot with errors.
What is the reason behind it ?
![Screenshot from 2019-12-19 14-54-31](https://user-images.githubusercontent.com/24788425/71159619-2de6bf80-2270-11ea-851c-0f1035973d9e.png)

**Comment by jordy25519** [comment]
The tutorial is slightly out of date with cennznet master branch so some types are missing. It's an easy fix: https://github.com/cennznet/xpay-runtime-tutorial/blob/03471e31adcc57bf0aafce0a7cf921bffc2db6a4/runtime/src/lib.rs#L233-L237 should be updated to match https://github.com/cennznet/cennznet/blob/ec299bfb0d5230ac2388ef021ee129205f8b8d4a/runtime/src/lib.rs#L228-L234

**Comment by nazmul49** [comment]
Thanks for your solution. It worked.

**Comment by cowboy-bebug** [comment]
@nazmul49 there were still a couple of missing types for cennzx-spot module, to cause `./script/build.sh` to fail. This PR fixes the issue: #3
