### ISSUE TITLE
Cargo build error on xpay-runtime-tutorial

### ISSUE THREAD

**Issue by nazmul49** [cennznet/xpay-runtime-tutorial#2]
After running build.sh script. I followed the next command "cargo build"
Found the following error.
Is it possible to setup node using this repo ?
![Screenshot from 2019-12-20 15-31-27](https://user-images.githubusercontent.com/24788425/71246283-88e7e780-2340-11ea-8e98-ee088fe32221.png)

**Comment by cowboy-bebug** [comment]
@nazmul49 the issue was caused by missing `Cargo.lock` files so cargo was confused which versions to download. This PR fixes the issue: https://github.com/cennznet/xpay-runtime-tutorial/pull/3
